### ISSUE TITLE
So.. what do you do with it?

### ISSUE THREAD

**Issue by petercwallis** [PetteriM1/BlockAPIExample#1]
I have nukkit server up and running, I can add plugins, and I know java, but how do I compile and run this example?

I need something in the classpath obviously to compile it with javac, and I guess I could create a jar and put it in the plugins directory is the next thing to try, but the documentation is a bit light on what needs to go in a plugin jar.  Even then, not sure I know how I would get an example block for my minecraft character.  Again I am guessing but presumably I should open chat and use a "/xxx" command to...  add it to my character's inventory perhaps?

The "natural" thing would be to make sure the class of the extended block is in my classpath and then presumably it needs registering somehow, and then it needs to be "crafted" into the inventory of a player somehow.  Is that right?

**Comment by PetteriM1** [comment]
This is just an example of the API but as most Nukkit plugins it can be compiled with Maven (`mvn package`).

The plugin just replaces a few vanilla blocks and the replaced blocks can be given normally using /give command.
